#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ Testing and building your project before pushing'

# Check tests 
npm run check-tests:push ||
(
    echo '❌ Tests Check Failed'
    false;
)

# Check build project tests 
npm run build ||
(
    echo '❌ Build Failed'
    false;
)

echo '✅ All checks is ok.'
